### PR TITLE
Keeping the system UI

### PR DESCRIPTION
**Pull request by mcwolfmm**
HI
I added settings for borders and margins on `JTextField`s in `DatePicker` and `TimePicker`.

My goal is to add the possibility of preserving the appearance of the controls do not differ from the rest in the form in which it is used. When given a null value for the item he is left unchanged. Thus maintaining his view such as it is defined by the current look and feel.

I removed generated by JFormDesigner method `initComponents()`, because layout that enjoys it creates more problems than it solves.

In FullDemo I have added examples of this functionality and the previous one.

### CODE REVIEW

**Comment by BlakeTNC** [comment]
Hello mcwolfmm, 
I was taking time to look through this pull request today. It looks like I will not be able to accept this pull in its current version. The reason is that certain sections of the code were originally created (and are automatically managed) by a program called "JFormDesigner". Those small sections of code cannot be modified by hand, they can only be modified from within the JFormDesigner program. It looks like you have changed these portions of the code, which would break the ability to use JFormDesigner in the future.

All the sections that should not be modified are marked with an automatically generated comment that looks something like this:
// JFormDesigner - Component initialization - DO NOT MODIFY  //GEN-BEGIN:initComponents

The functions that are managed by JFormDesigner include the following functions:
DatePicker.initComponents()
TimePicker.initComponents()

I have not found any other problems with your code yet, but there were a lot of sections to evaluate so I don't know for sure about the rest.

This is a tip that I once learned from other github developers: It's important to submit separate pull requests for each individual feature or issue that you are improving, instead of combining them into one big pull request. For example, if the Bulgarian translation was submitted separately, I would have no problem accepting it. I'm sure that I would also accept the fix for issue #38, and some of the of the features you included, if they were submitted separately. With so many different features submitted in a single request, it's harder for me to evaluate the quality and purpose of all the changed code at once.

Thank you for working on the project. With some changes, I'm sure we could incorporate most or all of your improvements.

warm regards,
Blake

**Comment by mcwolfmm** [comment]
Hi,
sorry for the big pull requests, just use that control and movement fix.

About this change (which conformed to let separately :)), i removed deliberately generated by `JFormDesigner` code. I also deliberately changed the name of the functions of `initComponents` to `initComponentsEx` to avoid a conflict if re-used `JFormDesigner` to generate.

The reason for this is that tools like `JFormDesigner` use its own layout (or one set of code generators). In these layouts, however, lacks a feature that is essential for similar components - the possibility of vertical positioning of the components.
This option is important because the panel controls `DatePicker` and `TimePicker` almost always used in another panel with other controls around it. If any of these controls is higher then the panel on which it is placed will be resized leading to resize the panels of `DatePicker` and / or `TimePicker`. This in turn will lead to a change in the position of controls on them. And so will lose vertical alignment.
This fact may be another function to be added - as in my option firmly aligned in the middle.

The use of `JFormDesigner` for the placement of two control together for me is unjustified, especially with the problem that I described above. So I think in `DatePicker` and `TimePicker` it should not be used.

**Comment by BlakeTNC** [comment]
Hello,
I believe I understand what you're saying. I did more exploration of your code. I'm not an expert in manually changing layouts, so this area is difficult for me. 

I did find some problems with your results, that I would like to report. See the following screen shot:

button problems

(1) (important) Notice that the spinner and drop down buttons are no longer always filling their vertical space. 

(2) (less important) I would prefer that the example icons in the demo remain scaled to their original size (not made smaller), to avoid the distortion that you can see in the screenshot. (I would not care much how the original scaling was implemented.)

Choice of JFormDesigner, or not: JFormDesigner can use any common layout manager that is desired, including GridBagLayout. You are correct, the DatePicker and TimePicker forms are relatively simple and so we do not necessarily have to use JFormDesigner. If we get these components working properly with some layout manager, it's possible that I could re-create the exact same layout in JFormDesigner afterwards.

Choice of layout: The reason that I have typically chosen "FormLayout" by default, is that it is an excellent, award-winning layout manager, and it was designed as an improvement to GridBagLayout.  FormLayout was created by the author of "JGoodies", not the author of JFormDesigner. It was included as an option in JFormDesigner because of its high popularity. In my experience, FormLayout is typically good at automatically avoiding the kinds of layout problem is that you can see highlighted in the screenshot.

Are you certain that you cannot use FormLayout to accomplish the changes that you wish to make? I don't know all the features of both layout managers, but I have imagined that FormLayout could do almost anything that GridBagLayout could do.

If you do want to use GridBagLayout, I would desire for these button alignment problems to be fixed somehow. I don't yet have the expertise in GridBagLayout to fix them myself.

Thank you for telling me your thoughts on this issue.

Warm regards,
Blake

**Comment by BlakeTNC** [comment]
PS, I added this code as a branch to the repository. The branch is named PR/40.
-Blake

**Comment by mcwolfmm** [comment]
Hi,
I made some changes to the code to evenly things you do not like.

Regarding the difference of the size of the text box and the panel with ths spinner buttons. The reason for the discrepancy is that there is no way two buttons have the same height equal to the height of the text box. If the height of the text field is even, the buttons are aligned well. But if it's odd there will always be one pixel difference (the spinner panel will always be one pixel or higher-short of the text box).
To turnips this problem, having two buttons have a different height (with a difference of one pixel, if necessary).
To realize I've put buttons directly into the panel of the TimePicker. So he takes care of setting the correct height.

Also I left unscaled images as requested. Of course, added logic that monitors the size of the toggle button and the text box and resizes all controls to the higher element.

Regarding the choice of layout, it depends entirely on you. If it can achieve the same effect in JFormDesigner with FormLayout (or other) do not know. Maybe in the original version simply did not select the correct options. But I notice many differences in height controls.

Metal Look and Feel
metal l f

Nimbus Look and Feel
nimbus l f

Motif Look and Feel
motif l f

GTK Look and Feel (linux)
gtk l f

Windows Classic Look and Feel
windows classic l f

Windows Look and Feel (windows XP)
windows l f

Also I did a test application which illustrate the need for vertical alignment of controls, regardless of the height of the parent container
```java
public class LGoodDatePickerTest extends JFrame {
	
	private DateTimePicker picker;

	public LGoodDatePickerTest() throws HeadlessException {
		setTitle("LGoodDatePicker Test");
		
		picker = new DateTimePicker();
	}
	
	protected void createGUI() {
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		
		picker.setPreferredSize(new Dimension(
				picker.getPreferredSize().width, 
				picker.getPreferredSize().height * 3
		));
		
		picker.setBackground(Color.RED);
		
		JPanel contentPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 0));
		contentPanel.setBackground(Color.YELLOW);
		
		contentPanel.add(new JLabel("Date and Time: "));
		contentPanel.add(picker);
		
		add(contentPanel, BorderLayout.CENTER);
		
		pack();
		setLocationRelativeTo(null);
	}
	
	protected void showFrame() {
		createGUI();
		setVisible(true);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String[] args) {
		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				LGoodDatePickerTest frm = new LGoodDatePickerTest();
				frm.showFrame();
			}
		});
	}
	
}
```
demo

**Pull request closed without merging**
