### PR TITLE
Moved images from /images to a package based folder

### PR DESCRIPTION
**Pull request by bjorndarri**
Moved images from /images folder to a package based folder under resources.

The images folder prevents a JarInputStream from locating the manifest file, which in turn hides the Automatic-Module-Name attribute from tools requiring it (such as Gradle).

See JarInputStream constructor comment:

// This implementation assumes the META-INF/MANIFEST.MF entry
// should be either the first or the second entry (when preceded
// by the dir META-INF/). It skips the META-INF/ and then
// "consumes" the MANIFEST.MF to initialize the Manifest object.

https://github.com/openjdk/jdk/blob/05a764f4ffb8030d6b768f2d362c388e5aabd92d/src/java.base/share/classes/java/util/jar/JarInputStream.java#L74

Here's what got me on the trail:
https://stackoverflow.com/a/63457166/317760

Which led to me to this:
https://github.com/gradle/gradle/blob/6bdd820e3a936cf82677f7e93728c2640fc80972/subprojects/core/src/main/java/org/gradle/internal/jvm/JavaModuleDetector.java#L154

Which then led to the JarInputStream issue.

### CODE REVIEW

**Comment by bjorndarri** [comment]
This effectively renders the Automatic-Module-Name attribute useless, which prevents me from (at least easily) using this fine library in a modular application.

**Comment by bjorndarri** [comment]
Oops, didn't mean to close this.

**Comment by bjorndarri** [comment]
Here's a simple test:
```
public static void main(String[] args) throws Exception {
  try (JarInputStream jarStream =  new JarInputStream(new FileInputStream("LGoodDatePicker-11.1.0.jar"))) {
    System.out.println(jarStream.getManifest() == null);
  }
}
```

**Comment by WiseEagleOwl** [comment]
@bjorndarri Thank you for proposing a fix for the issue you uncovered.
Based on your detailed input I have debugged the `JarInputStream` *class* and it indeed has a dependency on the order of *JarEntries* in the JAR-ZIP-file. As far as I understood it is required that in our case the first *JarEntry* has to be the **META-INF** folder directly followed by the **MANIFEST.MF** file. I suppose the order of *JarEntries* is dependent on the order in which files/folders were written to the underlying ZIP stream).

I could reproduce the part of your issue where the **MANIFEST.MF** is not found.
But I never encountered that the **image** folder was the first/second *JarEntry*. Did you run a full build with your changes and the produced * LGoodDatePicker*-JAR-file passed your own test?
```java
  try (JarInputStream jarStream =  new JarInputStream(new FileInputStream("LGoodDatePicker-11.1.0.jar"))) {
    if (jarStream.getManifest() != null) {
        System.out.println("passes");
    } else {
        System.out.println("fails");
    }
  }
```
For me the issue was that the **META-INF** *JarEntry* was directly followed by the **com** *JarEntry*. I suspect that moving the **image** folder will not fix the underlying issue.

What I think is causing the root issue is the shading process used in our build, where we replace the automatically generated **MANIFEST.MF** file with our own version, which contains the `Automatic-Module-Name` you are reliant on. This probably upsets the order in the ZIP stream because the new **MANIFEST.MF** file is probably the last file written into the stream. 
Sadly I am clueless as to how to fix this. I don't see any option of the `maven-shade-plugin` to influence the order of files written to the ZIP-stream. The relevant build configuration is this:
https://github.com/LGoodDatePicker/LGoodDatePicker/blob/3dbc9aa525928b0079852dd224e4e94c2cd5ae51/Project/pom.xml#L249-L280

**Comment by bjorndarri** [comment]
Thanks for clearing that up.

I'll be on the lookout for a solution to the actual issue :).

**Pull request closed without merging**
