### PR TITLE
Apply formatting to every PR instead of every push to master

### PR DESCRIPTION
**Pull request by WiseEagleOwl**
### I would like to propose the following changes to the code formatting *Github* action:
* Run it on every PR that is created, so that the code is already nicely formatted for the reviewer
* Do **not** run formatting on changes to the master branch. My reasoning for this is as follows:
  * All changes coming through PRs are now already formatted so in that case running it again is unnecessary
  * If there at any point in the future there is an issue with the formatting *Github* action (e.g. a corrupt formatter executable is downloaded) there would be broken commits that have been automatically committed to master
  * Having formatting changes applied to PRs ensures these changed are also reviewed and possible issues with it will be detected early on

@BlakeTNC if you want to keep the formatting on push to *master* I can add it back in.

### CODE REVIEW

**Comment by BlakeTNC** [comment]
This sounds good to me. Thank you.

**Comment by BlakeTNC** [comment]
The formatting action is failing, even when I rerun it. I don't know why.

**Comment by BlakeTNC** [comment]
failure log:
Committing changes
  /usr/bin/git commit --all -m Google Java Format
  [detached HEAD 9212f30] Google Java Format
   1 file changed, 6 insertions(+), 3 deletions(-)
  /usr/bin/git push
  fatal: You are not currently on a branch.
  To push the history leading to the current (detached HEAD)
  state now, use
  
git push origin HEAD:<name-of-remote-branch>
  
Error: The command 'git' failed with exit code 128

**Comment by WiseEagleOwl** [comment]
@BlakeTNC sorry about that 😳. *Github* actions seem to have a very different behavior for `on: pull_request` and for `on: push` I have not found a way to allow pushing changes successfully for the `on: pull_request` case. I have chosen an alternative approach in #158.

**Pull request merged**
