### PR TITLE
Drop support for Java 6 and Java 7

### PR DESCRIPTION
**Pull request by dbmalkovsky**
This is the implementation for this [issue](https://github.com/LGoodDatePicker/LGoodDatePicker/issues/143).

In the process also updated some dependencies in pom.xml to more current versions.

### CODE REVIEW

**Comment by BlakeTNC** [comment]
Hi David,
  Thanks for all your work.
I reviewed this latest pull. I was wondering why this code was removed?



I don't have reason to think this optional dependency is specific to the backport or Java 6/7, so you may want to put it back before I merge the pull. (I suggest keeping it, in commented form.) I have not looked into it closely though, so correct me if I'm wrong about it being specific to the backport.

Best,
Blake

**Comment by BlakeTNC** [comment]
@WiseEagleOwl Please disregard my review request. I accidentally clicked the review request button. 
Regarding: "BlakeTNC requested a review from WiseEagleOwl"

**Comment by dbmalkovsky** [comment]
Very good catch; I put the optional dependency block of code back.  Thank you.

**Comment by WiseEagleOwl** [comment]
@BlakeTNC your review request was an happy accident 🙂: changes to the *deploy* profile in `pom.xml` are not covered by the CI tests. I've just now executed the github deploy action with these changes to verify that the release can be generated and the output remains the same.

**Pull request merged**
