### PR TITLE
Add tests for custom clock feature

### PR DESCRIPTION
**Pull request by WiseEagleOwl**
This *PR* provides:
* new tests for the feature added in *PR* #90 
* fixes two bugs encountered while writing these tests
  * Missing call to `settings.getClock()`
https://github.com/LGoodDatePicker/LGoodDatePicker/blob/73476fe38fe23facd3b088b5438ead370d14f37d/Project/src/main/java/com/github/lgooddatepicker/components/TimePicker.java#L679-L681
  * One constructor of `CalenderPanel` threw an exception
https://github.com/LGoodDatePicker/LGoodDatePicker/blob/73476fe38fe23facd3b088b5438ead370d14f37d/Project/src/main/java/com/github/lgooddatepicker/components/CalendarPanel.java#L210-L212
as the changed line below from *PR* #90 directly accessed `datePickerSettings` even if it was `null`
https://github.com/LGoodDatePicker/LGoodDatePicker/blob/73476fe38fe23facd3b088b5438ead370d14f37d/Project/src/main/java/com/github/lgooddatepicker/components/CalendarPanel.java#L253
* increases the version to `v11.0.1` due to the bug fixes

### CODE REVIEW

**Comment by WiseEagleOwl** [comment]
@ArchieBlack  can you take a quick look at these changes and comment here if they look okay to you?
The relevant changes are lines 253, 1023, 1101 and 1828-1835 in `CalenderPanel.java` as well as line 680 in `TimerPicker.java`

**Comment by ArchieBlack** [comment]
Great catch.  Sorry about missing that NPE!  The tests look good to me.

**Comment by WiseEagleOwl** [comment]
Thanks for your timely reponse! No worries regarding that `NullpointerException` everyone makes mistakes. That's why I write so many tests and introduced continous builds+tests for this repo.

**Comment by ArchieBlack** [comment]
Is 11.0.1 going to be pushed as a release or just internal?  It's not on the front page or maven yet.

**Comment by WiseEagleOwl** [comment]
`v11.0.1` is not yet released. The problem is that there are not enough automated tests yet to know for sure that the release `v11.0.0` didn't break anything major for a majority of the user base. Therefore I will have to wait for user feedback to know for sure. If issues come up they will be fixed and a new version `v11.0.2` will be released. If no issues come up in the next two weeks this `v11.0.1` version will be published.
If the bugs addressed in `v11.0.1` cause a major issue for you let me know and we will find a solution.
In general I'm very interested in user feedback. Did you test *LGoodDatePicker* `v11.0.0` already? Even if there were no issues I'd like to know which OS (Linux/Windows/Mac) and Java version were used. Knowing which OS and Java versions did not cause any issues so far is very valuable to me. I only had the opportunity to test under Windows using OpenJDK 11.0.8.10 so far.

**Comment by ArchieBlack** [comment]
Open JDK 11.0.3, Oracle JDK 1.8 windows and linux.  Pretty limited use case but with the new Clock feature attached to Date Picker with the calendar popup.   Did not suffer from the NPE in my use case.

**Comment by BlakeTNC** [comment]
I've run v11.0.0 demo on macos catalina, jdk 8 and 14.

**Pull request merged**
