### PR TITLE
Format source using spotless Maven plugin

### PR DESCRIPTION
**Pull request by WiseEagleOwl**
After reading the discussion in #150 I started to look into available code formatters.
The Docs of  *Google Java Style* recommended using the `spotless-maven-plugin` to format the source. I tried to implement that. Sadly the `google.java-format` part of this plugin has issues as reported here: https://github.com/diffplug/spotless/issues/834

So I decided to go with with an `<eclipse>` based formatting. I based the *Eclipse* formatting on the `Preferences-Java-CodeStyle-Formatter.xml` from #150.
I added a few tweaks to keep the changes to the code to a minimum.

The formatting wil executed for every compilation of the project, regardless of the used IDE.

This PR is a draft to show how this formatting will look like.

### CODE REVIEW

**Comment by dbmalkovsky** [comment]
I would still lean towards the google style.  There are IDE plugins for NetBeans, IntelliJ, and Eclipse.   That way we don't have to manage the style and there is a third party that decides when we don't agree 😄.

The google page clearly outlines the issue with the plugin and JDK 16 and after including the workaround; https://github.com/google/google-java-format#jdk-16

Using the combination all things are covered.

As for this draft I noticed the larger indentation of 8 spaces that Blake didn't seem to like and there are a number of files where package level import statement are still present.

**Comment by WiseEagleOwl** [comment]
@dbmalkovsky 
IDE plugins are not mandatory or requited for this solution: Maven will format all source once you compile.

Regarding *GoogleJavaFormat*: the workaround i.e. providing special arguments for the Java VM will create more complexity in our CI actions as we cannot supply these options to a Java 8 VM (that one will exit with *unknown argument* error).
So we have the trade-off of not having to manage or argue over the details of the style and having to maintain a CI system that has more special case code for specific java versions.

> As for this draft I noticed the larger indentation of 8 spaces that Blake didn't seem to like and there are a number of files where package level import statement are still present.

* By larger indentation, do you mean `formatter.continuation_indentation`? 
I have just now reduced the continuation indentation to 4 spaces.
* I'm not quite clear on what you refer to with "package level import statement" the Eclipse formatter will only reorder import statements and has no resolution logic. Therefore changes going further than ordering are not to be expected.

**Comment by dbmalkovsky** [comment]
> * I'm not quite clear on what you refer to with "package level import statement" the Eclipse formatter will only reorder import statements and has no resolution logic. Therefore changes going further than ordering are not to be expected.

What I mean is statements like _import java.awt.*;_

The google formatting tools know how to expand that and remove any unused imports.

**Comment by dbmalkovsky** [comment]
> Regarding _GoogleJavaFormat_: the workaround i.e. providing special arguments for the Java VM will create more complexity in our CI actions as we cannot supply these options to a Java 8 VM (that one will exit with _unknown argument_ error).
> So we have the trade-off of not having to manage or argue over the details of the style and having to maintain a CI system that has more special case code for specific java versions.

I'm not a CI workflow expert but there are different blocks to invoke each JDK/operating system pair isn't there?  So it is just adding the parameters to the JDK 17 blocks isn't it?

I'll accept whatever others decide and not try to grumble too much. 😃

**Comment by WiseEagleOwl** [comment]
@dbmalkovsky Got it! I only knew them as "wildcard import statements"

*GoogleJavaFormat* also did not resolve any wildcard imports when run on my machine, am I missing some option?

**Comment by dbmalkovsky** [comment]
Sorry; 😭 my mistake.  I was using the Google Style Plugin in IntelliJ and it did it there.   I assumed the "batch" version behaved the same.   That is what I get for assuming things.

**Comment by WiseEagleOwl** [comment]
> I'm not a CI workflow expert but there are different blocks to invoke each JDK/operating system pair isn't there? So it is just adding the parameters to the JDK 17 blocks isn't it?

Sadly it's not that simple: 
* IMO the biggest advantage of automatic code formatting in OSS is that it makes it easier for new contributors to propose changes as they don't have to manually adhere to any style guide
* Most new contributors run fairly recent java versions as it allows the usage a newer language features.
* If a new contributor tries to build this project locally with a JDK > 16 he would get cryptic error messages as the correct command line is only supplied in CI
* This would be demotivating for new contributors and absolutely not what we want. 
* It is very much preferable if this projects runs of the box locally for all JDKs > 8.
* This means the *GoogleJavaFormat* command line options have to be part of the default maven configuration
* This makes things a bit complicated because now we have to remove these command line options if we run on JDK 8 in CI for tests and releases.

All this is possible to implement but its not very straightforward.

**Comment by BlakeTNC** [comment]
I tested a github action to apply google style to the master branch upon any github commit. See pull request #152. For clarity, I will continue discussion of this experiment under that pull request. I invite you to review the proposed changes, and comment further over there.

**Comment by BlakeTNC** [comment]
PS, I have not yet looked very deeply into the eclipse based style proposed here by @WiseEagleOwl, for reasons described below. 

If feasible, I am currently in favor of using the Google Java Style (aka "google style"), and I have an impression that this PR #151 does not implement the google style. Let me know if I am mistaken on that impression. 

Also please let me know if any of the possible bugs or issues that were discussed here and in (https://github.com/diffplug/spotless/issues/834), would affect the repository-level solution that is attempted in PR #152.

**Comment by WiseEagleOwl** [comment]
@BlakeTNC If you prefer the Google Java Style than that's okay with me. I will close this PR then (it does indeed not implement the google style). 

Your repository level solution does not have the issues I outlined in my comment 👍

**Comment by BlakeTNC** [comment]
@WiseEagleOwl Thank you for your work on this anyway. Much appreciated.

**Pull request closed without merging**
