### PR TITLE
Added a method to manually set the dimension of the datepicker JTextField

### PR DESCRIPTION
**Pull request by Gittino**
Hi Blake,
I did a very small change to your component to allow to set the datepicker JTextField dimension.
Maybe you can merge it in the next official version.
Feel free to change, rewrite or refuse the change if you don't like it.
Thanks and best regards.

### CODE REVIEW

**Comment by BlakeTNC** [comment]
Hi Gittino, 
As of LGoodDatePicker 5.3.1, the programmer can manually change the dimension of the text field using the function: DatePickerSettings.setSizeTextFieldMinimumWidth(). (Thank you for the effort to fix the issue, but I will be declining the pull request, because it duplicates the above functionality.)

Just so you know, after you upgrade to 5.3.1, you probably would not need to manually change the width because the date picker now has a new default sizing behavior. It dynamically resizes itself to to this date format that is applied (and the locale and font). So with your previously described problem, the date picker would now be the appropriate size for your smaller numeric format.

Let me know if this enhancement works for you.

warm regards,
Blake

**Comment by Gittino** [comment]
Hi Blake, 
the fix that I proposed fix also the issue related to the height of the text field when for example the nimbus look and feel is used.
Setting the size manually allows the programmer to make all the text fields of the UI of the same height.
Maybe you can take my update as example and implement a method similar to setSizeTextFieldMinimumWidth that set the height like setSizeTextFieldHeigh instead of a Dimension as in my change.
Best regards.

**Comment by BlakeTNC** [comment]
I see. Yes, I could implement a function to manually set the height pretty easily.  I'd want to put it in DatePickerSettings of course, with the rest of those kinds of functions. I will add this to the todo list.
Thank you.

**Comment by Gittino** [comment]
Great thank you very much,
effectively putting it into the DatePickerSettings has much more sense, I didn't considered the structure of the component, I just write some quick and dirty code to reach the objective.
Thanks!

**Pull request closed without merging**
