### PR TITLE
Add Finnish translation

### PR DESCRIPTION
**Pull request by fluks**

### CODE REVIEW

**Comment by BlakeTNC** [comment]
@fluks,
It looks good. Merging this. Thank you for the contribution. : )
-Blake

**Comment by BlakeTNC** [comment]
PS, I also added the Finnish translation to the full demo (and committed the change). It looks like it is working properly.

**Comment by fluks** [comment]
I tried it also in the demo and it appeared to work. I just wasn't sure if I should add it to the commit. Thank you.

**Comment by BlakeTNC** [comment]
Cool. You're welcome.

**Pull request merged**
