### PR TITLE
Fix deprecation and unchecked compiler warnings

### PR DESCRIPTION
**Pull request by WiseEagleOwl**
This pull request provides fixes for all unchecked and deprecated warnings in the library.
These are a byproduct of my work on the recent fixes.
- ceb2d57 activates the compiler warnings so that new warnings can easily detected in the future. 
I can drop this commit from the branch if this change is not wanted.
- b152331 contains fixes for most of the unchecked and deprecation warnings
- 610a46a contains fixes for unchecked warnings in files where comments state they were auto-generated by *JFormDesigner*. 
If these changes are unwanted I can drop this commit from the branch.

All tests pass with the changes in this pull request. I also used the *LGoodDatePicker Demo* to user-test controls and did not find any issues.

### CODE REVIEW

**Comment by BlakeTNC** [comment]
@WiseEagleOwl, I invited you to have "Triage" collaborator access to this repository.  I think it means you will be able to "manage" the github issues you have been fixing. If you wish to comment on the fixed issues (to describe your fix), and then close them, feel free to do so. If you don't have the power to close the issues as expected, let me know. 
-BlakeTNC

**Comment by WiseEagleOwl** [comment]
@BlakeTNC, I’m happy to help :slightly_smiling_face:. I closed all issues that were solved with the recently merged PRs. 
Just let me know if you need help with anything else.

**Comment by BlakeTNC** [comment]
@WiseEagleOwl, I upgraded your role on this repository to "Maintain" for LGoodDatePicker, which I believe means you can do pretty much anything except delete the repository. Also, if you don't mind will you sent me your email address, so we can contact each other if ever needed? Don't post it here, this form works instead. https://www.emailmeform.com/builder/form/ZQcYut4393

**Comment by WiseEagleOwl** [comment]
@BlakeTNC, thank you for adding me as a maintainer. I will try my best to help you maintain *LGoodDatePicker*. 
I've just sent you a message via the email form you provided.

**Pull request merged**
