### PR TITLE
Use maven-jar-plugin to attach the custom manifest file

### LINKED ISSUE #122: JarInputStream fails to locate the manifest file in LGoodDatePicker.jar
Executing the following Code on a current *LGoodDatePicker* release JAR file outputs **"fails"**:
```java
try (JarInputStream jarStream =  new JarInputStream(new FileInputStream("LGoodDatePicker-11.1.0.jar"))) {
    if (jarStream.getManifest() != null) {
        System.out.println("passes");
    } else {
        System.out.println("fails");
    }
}
```
The reason for this is that the `JarInputStream` assumes that the first two `JarEntry`s contain the **MANIFEST.MF** file or the **META-INF** folder directly followed by the **MANIFEST.MF** file.

```java
public JarInputStream(InputStream in, boolean verify) throws IOException {
        super(in);
        this.doVerify = verify;

        // This implementation assumes the META-INF/MANIFEST.MF entry
        // should be either the first or the second entry (when preceded
        // by the dir META-INF/). It skips the META-INF/ and then
        // "consumes" the MANIFEST.MF to initialize the Manifest object.
        JarEntry e = (JarEntry)super.getNextEntry();
        if (e != null && e.getName().equalsIgnoreCase("META-INF/"))
            e = (JarEntry)super.getNextEntry();
        first = checkManifest(e);
    }
```
see [the code here](https://github.com/openjdk/jdk/blob/a6a7e4398aae9568e39650341aa3255ab23f9961/src/java.base/share/classes/java/util/jar/JarInputStream.java#L74-L86)

This assumption fails for *LGoodDatePicker* JAR files because we use the *maven-shade-plugin* to remove the default *MANIFEST.MF* from the JAR file and add a custom one instead. This supposedly places the new *MANIFEST.MF* file at the end of the JAR stream, not the beginning. As a result our new **MANIFEST.MF** file is not found by `JarInputStream`.
https://github.com/LGoodDatePicker/LGoodDatePicker/blob/3dbc9aa525928b0079852dd224e4e94c2cd5ae51/Project/pom.xml#L249-L280

### PR DESCRIPTION
**Pull request by WiseEagleOwl**
This *PR* provides
------------------------
* Fix #122:
Using the *maven-shade-plugin* to attach the custom manifest file leads to the issue that the manifest file is not at the beginning of the JAR stream. This is resolved by using the *maven-jar-plugin* to attach the custom manifest file.

### CODE REVIEW

**Comment by WiseEagleOwl** [comment]
@bjorndarri Can you please verify that this resolves your issue?
A temporary test version can be found in [this](https://oss.sonatype.org/content/repositories/comgithublgooddatepicker-1030) staging repository with version `11.2.1-test`. You can add this test repository to your *Gradle* build like this:
```gradle
repositories {
   //all your default repositories...
  maven {
        url "https://oss.sonatype.org/content/repositories/comgithublgooddatepicker-1030"
    }
}
```

**Comment by bjorndarri** [comment]
At first glance it looks like this solves the problem, I'll do some further testing in a properly modular project tonight, I'll report back.

**Comment by bjorndarri** [comment]
Couldn't wait, finished testing this and I can confirm that this does indeed solve the problem.

ps. sorry about that weird solution proposed yesterday, I was so deep down the debugging rabbit hole, having spent hours searching for a solution that I just jumped on the first thing that looked like it fixed the problem, even though it was so obviously wrong :).

**Comment by WiseEagleOwl** [comment]
No worries, tunnel vision on the bug hunt happens to everyone :slightly_smiling_face:. You left enough bread crumbs for me to find the root cause, that is what matters :+1: 

Thank you for taking the time to verify my solution. FYI the release process for *LGoodDatePicker* `v11.2.1` containing this fix will probably begin next week. Your special test version will vanish once a preview release for `v11.2.1` is published.

**Pull request merged**
